-- MySQL Script generated by MySQL Workbench
-- Sat Nov 26 23:33:13 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema muggle_news
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `muggle_news` ;

-- -----------------------------------------------------
-- Schema muggle_news
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `muggle_news` DEFAULT CHARACTER SET utf8 ;
USE `muggle_news` ;

-- -----------------------------------------------------
-- Table `muggle_news`.`pre_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muggle_news`.`pre_users` ;

CREATE TABLE IF NOT EXISTS `muggle_news`.`pre_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `referrer` VARCHAR(255) NULL,
  `user_agent` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
