-- MySQL Script generated by MySQL Workbench
-- Sun Dec  4 01:40:59 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema muggle_news
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `muggle_news` ;

-- -----------------------------------------------------
-- Schema muggle_news
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `muggle_news` DEFAULT CHARACTER SET utf8 ;
USE `muggle_news` ;

-- -----------------------------------------------------
-- Table `muggle_news`.`pre_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muggle_news`.`pre_users` ;

CREATE TABLE IF NOT EXISTS `muggle_news`.`pre_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `referrer` VARCHAR(255) NULL,
  `user_agent` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `muggle_news`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muggle_news`.`users` ;

CREATE TABLE IF NOT EXISTS `muggle_news`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(500) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `profile_img` VARCHAR(500) NULL,
  `fb_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `fb_id_UNIQUE` (`fb_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `muggle_news`.`timelines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muggle_news`.`timelines` ;

CREATE TABLE IF NOT EXISTS `muggle_news`.`timelines` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `cover_img` VARCHAR(500) NULL,
  `title` VARCHAR(100) NOT NULL,
  `subtitle` VARCHAR(200) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_timelines_users_idx` (`user_id` ASC),
  INDEX `idx_created_at` (`created_at` ASC),
  INDEX `idx_updated_at` (`updated_at` ASC),
  CONSTRAINT `fk_timelines_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `muggle_news`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `muggle_news`.`previews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muggle_news`.`previews` ;

CREATE TABLE IF NOT EXISTS `muggle_news`.`previews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `title` VARCHAR(100) NOT NULL,
  `content` VARCHAR(1000) NOT NULL,
  `preview_img` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `muggle_news`.`items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muggle_news`.`items` ;

CREATE TABLE IF NOT EXISTS `muggle_news`.`items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `title` VARCHAR(100) NOT NULL,
  `content` VARCHAR(1000) NULL,
  `timeline_id` INT NOT NULL,
  `preview_id` INT NOT NULL,
  PRIMARY KEY (`id`, `preview_id`, `timeline_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_items_timelines1_idx` (`timeline_id` ASC),
  INDEX `fk_items_previews1_idx` (`preview_id` ASC),
  INDEX `idx_created_at` (`created_at` ASC),
  INDEX `idx_updated_at` (`updated_at` ASC),
  CONSTRAINT `fk_items_timelines1`
    FOREIGN KEY (`timeline_id`)
    REFERENCES `muggle_news`.`timelines` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items_previews1`
    FOREIGN KEY (`preview_id`)
    REFERENCES `muggle_news`.`previews` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
